### ISSUE TITLE
Unable to start service Intent IBeaconService 

### ISSUE THREAD

**Issue by saifrahmed** [RadiusNetworks/proximity-reference-android#2]
Hello,
When launching the proximity (v1.1.0) reference application, the reference application seems to launch fine, but not the service library.  I get the below error:
04-22 02:47:27.467: W/ActivityManager(580): Unable to start service Intent { cmp=com.radiusnetworks.proximity.androidproximityreference/com.radiusnetworks.ibeacon.service.IBeaconService } U=0: not found

Also note, it does not pick up either of the beacons I have active (Dev Kit w/ upgrade; MacBeacon)

**Comment by davidgyoung** [comment]
Saif,

It looks like the combined manifest in your application is not begin generated properly.  A Few things to check:
1. You must have an Eclipse with ADT Plugin version 21 or higher.  To see this version in Eclipse, please go to Help -> Install New Software -> what's already installed, then look for the version associated with the line item "Android Development Tools"
2. If you have the proper version, double check that your dependency between AndroidProximityReference is set up properly in Eclipse.   Select AndroidProximityReference  in the project navigator, then select Project -> Properties -> Android and verify that your setup looks like the attached screenshot.
3. Please verify that your generated AndroidManifest.xml has the proper service definitions.  In the AndroidProximityReference project, please open the bin/AndroidManifest.xml file (make sure it is the one in the bin directory) and verify it contains a block that looks like this:
   
   `<service android:enabled="true" android:exported="true" android:isolatedProcess="false" android:label="iBeacon" android:name="com.radiusnetworks.ibeacon.service.IBeaconService></service>`

Thanks,
David

![screen shot 2014-04-22 at 3 53 54 pm](https://cloud.githubusercontent.com/assets/1044849/2769949/2d84b392-ca58-11e3-8518-1b0004cc1e20.png)
